# Inverse of Reynolds Number
Parfile.ins_invReynolds = 5e-3

# 1/Fr**2, Fr (Froude Number)
Parfile.ins_gravY = -1.0

# Gas density and viscosity scaled by liquid
Parfile.mph_rhoGas = 1.2e-3
Parfile.mph_muGas = 2.5e-4
Parfile.mph_iPropSmear = 1.5

# Gas thermal conductivity and specific heat
Parfile.mph_thcoGas = 2e-1
Parfile.mph_CpGas = 7e-1

# Stefan number
Parfile.mph_Stefan = 4e-3

# Prandtl number
Parfile.ht_Prandtl = 7.0

# Inverse Weber Number
Parfile.mph_invWeber = 2e-2

# bubble radius
Parfile.sim_bubbleRadius = 0.25

#       Grid dimensionality and geometry
Parfile.geometry = "cartesian"

#       Size of computational volume
Parfile.xmin = -0.75
Parfile.xmax = 0.75
Parfile.ymin = -0.5
Parfile.ymax = 2.5
Parfile.zmin = -0.75
Parfile.zmax = 0.75

#       Boundary conditions
Parfile.xl_boundary_type = "noslip_ins"
Parfile.xr_boundary_type = "noslip_ins"
Parfile.yl_boundary_type = "noslip_ins"
Parfile.yr_boundary_type = "outflow_ins"
Parfile.zl_boundary_type = "noslip_ins"
Parfile.zr_boundary_type = "noslip_ins"

#       Simulation (grid, time, I/O) parameters
Parfile.run_comment = "Evaporating Bubble problem"
Parfile.log_file = "INS_Evaporating_Bubble.log"
Parfile.basenm = "INS_Evaporating_Bubble_"
Parfile.restart = ".false."
Parfile.nend = 10000000
Parfile.tmax = 10
Parfile.ins_cflFlg = 0
Parfile.ins_cfl = 0.05
Parfile.ins_sigma = 0.05
Parfile.ins_dtSpec = 0.25e-4  # 0.025e-4  # 0.015625e-4 #1.0e-4
Parfile.dtinit = 0.25e-4  # 0.025e-4  # 0.015625e-4 #1.0e-4
Parfile.dtmax = 0.25e-4  # 0.025e-4  # 0.015625e-4 #1.0e-4
Parfile.tstep_change_factor = 1.0
Parfile.ins_pressureCorrect = ".false."

Parfile.plot_var_1 = "pres"
Parfile.plot_var_2 = "velx"
Parfile.plot_var_3 = "vely"
Parfile.plot_var_4 = "dfun"
Parfile.plot_var_5 = "temp"
Parfile.plot_var_6 = "mflx"

Parfile.checkpointFileIntervalTime = 1.0
Parfile.checkpointFileIntervalStep = 0

Parfile.plotFileIntervalTime = 1.0
Parfile.plotFileIntervalStep = 0

# AMR parameters
Parfile.nblockx = 6  # 18  # 24 #12 #6  #3
Parfile.nblocky = 12  # 36  # 48 #24 #12 #6
Parfile.nblockz = 6  # 18  # 24 #12 #6  #3
Parfile.nrefs = 10

Parfile.lrefine_min = 1
Parfile.lrefine_max = 1

# 	Runtime parameters for the Rising Bubble problem.
Parfile.gr_pmRpDivergenceFree = 1
Parfile.gr_pmRpNfieldDivf = 2
Parfile.gr_pmRpConsvFluxes = ".TRUE."
Parfile.gr_pmRpConsvFluxDensities = ".FALSE."

# Settings for guard cell filling
Parfile.gr_bcEnableApplyMixedGds = ".FALSE."
Parfile.convertToConsvdForMeshCalls = ".FALSE."
Parfile.convertToConsvdInMeshInterp = ".FALSE."
Parfile.enableMaskedGCFill = ".FALSE."

# 	Flux Conservation for AMR
Parfile.flux_correct = ".true."

# AMReX Poisson Solver Parameters
Parfile.gr_amrexMG_composite_solve = ".TRUE."
Parfile.gr_amrexMG_Tol = 1e-13
Parfile.gr_amrexMG_max_iter = 200

# HYPRE Poisson Solver Parameters
Parfile.gr_hyprePrintSolveInfo = ".FALSE."
Parfile.gr_hyprePcType = "HYPRE_AMG"
Parfile.gr_hypreSolverType = "HYPRE_BICGSTAB"
Parfile.gr_hypreRelTol = 1.0e-12
Parfile.gr_hypreFloor = 1.0e-16
